import "dotenv/config";
import mongoose from "mongoose";
import Question from "../src/models/Question.js";

const QUESTIONS = [
  // easy
  {
    slug: "two-sum",
    title: "two sum",
    difficulty: "easy",
    topics: ["arrays", "hashmaps"],
    statement: "given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to target. you may assume each input has exactly one solution and you cannot use the same element twice.",
    examples: [
      { input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "nums[0] + nums[1] == 9" },
    ],
    constraints: ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9"],
    hints: ["a brute force is two nested loops. can a hashmap make it one pass?"],
  },
  {
    slug: "valid-parentheses",
    title: "valid parentheses",
    difficulty: "easy",
    topics: ["strings", "stacks"],
    statement: "given a string containing only `()[]{}`, determine if every opening bracket is closed by the same type and in correct order.",
    examples: [{ input: "s = \"()[]{}\"", output: "true" }, { input: "s = \"(]\"", output: "false" }],
    constraints: ["1 <= s.length <= 10^4"],
    hints: ["think about a stack. when you see opening, push. on closing, check the top."],
  },
  {
    slug: "reverse-linked-list",
    title: "reverse linked list",
    difficulty: "easy",
    topics: ["linked lists"],
    statement: "given the head of a singly linked list, reverse the list and return the new head.",
    examples: [{ input: "1 -> 2 -> 3 -> 4 -> 5", output: "5 -> 4 -> 3 -> 2 -> 1" }],
    constraints: ["0 <= list length <= 5000"],
    hints: ["iterate with three pointers: prev, curr, next."],
  },
  {
    slug: "merge-two-sorted-lists",
    title: "merge two sorted lists",
    difficulty: "easy",
    topics: ["linked lists"],
    statement: "merge two sorted linked lists into one sorted list. the new list should be made by splicing together the nodes of the first two lists.",
    examples: [{ input: "l1 = [1,2,4], l2 = [1,3,4]", output: "[1,1,2,3,4,4]" }],
    constraints: ["0 <= length of each list <= 50"],
    hints: ["use a dummy head node to simplify edge cases."],
  },
  {
    slug: "maximum-subarray",
    title: "maximum subarray",
    difficulty: "easy",
    topics: ["arrays", "dp"],
    statement: "find the contiguous subarray with the largest sum and return its sum.",
    examples: [{ input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6", explanation: "subarray [4,-1,2,1]" }],
    constraints: ["1 <= nums.length <= 10^5"],
    hints: ["kadane's algorithm. at each index, decide: extend or start fresh?"],
  },
  {
    slug: "climbing-stairs",
    title: "climbing stairs",
    difficulty: "easy",
    topics: ["dp"],
    statement: "you climb stairs. each step you can climb 1 or 2 steps. how many distinct ways can you reach the nth step?",
    examples: [{ input: "n = 3", output: "3", explanation: "1+1+1, 1+2, 2+1" }],
    constraints: ["1 <= n <= 45"],
    hints: ["fibonacci sequence in disguise."],
  },
  {
    slug: "best-time-to-buy-and-sell-stock",
    title: "best time to buy and sell stock",
    difficulty: "easy",
    topics: ["arrays", "dp"],
    statement: "given an array `prices` where `prices[i]` is the stock price on day `i`. choose one day to buy and a later day to sell. return the maximum profit, or 0 if impossible.",
    examples: [{ input: "prices = [7,1,5,3,6,4]", output: "5", explanation: "buy at 1, sell at 6" }],
    constraints: ["1 <= prices.length <= 10^5"],
    hints: ["track the minimum seen so far. update max profit."],
  },
  {
    slug: "contains-duplicate",
    title: "contains duplicate",
    difficulty: "easy",
    topics: ["arrays", "hashmaps"],
    statement: "given an integer array, return true if any value appears at least twice. otherwise false.",
    examples: [{ input: "nums = [1,2,3,1]", output: "true" }],
    constraints: ["1 <= nums.length <= 10^5"],
    hints: ["a hashset gives o(n) time."],
  },
  {
    slug: "invert-binary-tree",
    title: "invert binary tree",
    difficulty: "easy",
    topics: ["trees", "recursion"],
    statement: "given the root of a binary tree, invert the tree (mirror it left-right) and return its root.",
    examples: [{ input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]" }],
    constraints: ["0 <= number of nodes <= 100"],
    hints: ["recursion: swap children, recurse on both."],
  },
  {
    slug: "valid-palindrome",
    title: "valid palindrome",
    difficulty: "easy",
    topics: ["strings"],
    statement: "given a string `s`, return true if it is a palindrome after lowercasing and removing non-alphanumeric characters.",
    examples: [{ input: "s = \"A man, a plan, a canal: Panama\"", output: "true" }],
    constraints: ["1 <= s.length <= 2 * 10^5"],
    hints: ["two pointers from both ends."],
  },

  // medium
  {
    slug: "longest-substring-without-repeating-characters",
    title: "longest substring without repeating characters",
    difficulty: "medium",
    topics: ["strings", "hashmaps"],
    statement: "given a string `s`, find the length of the longest substring without repeating characters.",
    examples: [{ input: "s = \"abcabcbb\"", output: "3", explanation: "the answer is \"abc\"" }],
    constraints: ["0 <= s.length <= 5 * 10^4"],
    hints: ["sliding window with a hashmap of last seen index."],
  },
  {
    slug: "3sum",
    title: "3sum",
    difficulty: "medium",
    topics: ["arrays"],
    statement: "given an integer array `nums`, return all unique triplets `[a,b,c]` such that `a + b + c == 0`. the solution must not contain duplicate triplets.",
    examples: [{ input: "nums = [-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]" }],
    constraints: ["3 <= nums.length <= 3000"],
    hints: ["sort. fix one element, two-pointer the rest."],
  },
  {
    slug: "container-with-most-water",
    title: "container with most water",
    difficulty: "medium",
    topics: ["arrays"],
    statement: "given `n` non-negative integers representing heights, find two lines that with the x-axis form a container holding the most water.",
    examples: [{ input: "height = [1,8,6,2,5,4,8,3,7]", output: "49" }],
    constraints: ["2 <= height.length <= 10^5"],
    hints: ["two pointers from both ends. move the shorter one."],
  },
  {
    slug: "group-anagrams",
    title: "group anagrams",
    difficulty: "medium",
    topics: ["strings", "hashmaps"],
    statement: "given an array of strings, group the anagrams together. anagrams have the same characters in different order.",
    examples: [{ input: "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", output: "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]" }],
    constraints: ["1 <= strs.length <= 10^4"],
    hints: ["use sorted string or character count tuple as the hash key."],
  },
  {
    slug: "product-of-array-except-self",
    title: "product of array except self",
    difficulty: "medium",
    topics: ["arrays"],
    statement: "given an array, return an array where `output[i]` is the product of every element except `nums[i]`. solve in o(n) time without division.",
    examples: [{ input: "nums = [1,2,3,4]", output: "[24,12,8,6]" }],
    constraints: ["2 <= nums.length <= 10^5"],
    hints: ["two passes: prefix products then suffix products."],
  },
  {
    slug: "coin-change",
    title: "coin change",
    difficulty: "medium",
    topics: ["dp"],
    statement: "given coin denominations and a total amount, return the fewest number of coins needed to make up that amount. return -1 if impossible.",
    examples: [{ input: "coins = [1,2,5], amount = 11", output: "3", explanation: "5+5+1" }],
    constraints: ["1 <= coins.length <= 12", "0 <= amount <= 10^4"],
    hints: ["bottom-up dp: dp[i] = min(dp[i-coin] + 1) for each coin."],
  },
  {
    slug: "longest-palindromic-substring",
    title: "longest palindromic substring",
    difficulty: "medium",
    topics: ["strings", "dp"],
    statement: "given a string `s`, return the longest palindromic substring in `s`.",
    examples: [{ input: "s = \"babad\"", output: "\"bab\" or \"aba\"" }],
    constraints: ["1 <= s.length <= 1000"],
    hints: ["expand around each center (n centers for odd length, n-1 for even)."],
  },
  {
    slug: "validate-binary-search-tree",
    title: "validate binary search tree",
    difficulty: "medium",
    topics: ["trees", "recursion"],
    statement: "given the root of a binary tree, determine if it is a valid binary search tree (left subtree < node < right subtree, recursively).",
    examples: [{ input: "[2,1,3]", output: "true" }, { input: "[5,1,4,null,null,3,6]", output: "false" }],
    constraints: ["1 <= number of nodes <= 10^4"],
    hints: ["pass min/max bounds down. or do an inorder traversal and check it's sorted."],
  },
  {
    slug: "number-of-islands",
    title: "number of islands",
    difficulty: "medium",
    topics: ["graphs", "recursion"],
    statement: "given an m x n grid of '1's (land) and '0's (water), count the number of islands. an island is land connected 4-directionally.",
    examples: [{ input: "[[1,1,0],[0,1,0],[0,0,1]]", output: "2" }],
    constraints: ["1 <= m, n <= 300"],
    hints: ["dfs or bfs from each unvisited land cell."],
  },
  {
    slug: "binary-tree-level-order-traversal",
    title: "binary tree level order traversal",
    difficulty: "medium",
    topics: ["trees"],
    statement: "given the root of a binary tree, return the level order traversal of its nodes' values (level by level).",
    examples: [{ input: "[3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]" }],
    constraints: ["0 <= number of nodes <= 2000"],
    hints: ["bfs with a queue. process level by level."],
  },
  {
    slug: "rotate-image",
    title: "rotate image",
    difficulty: "medium",
    topics: ["arrays"],
    statement: "given an n x n 2d matrix representing an image, rotate it by 90 degrees clockwise. do it in-place.",
    examples: [{ input: "[[1,2,3],[4,5,6],[7,8,9]]", output: "[[7,4,1],[8,5,2],[9,6,3]]" }],
    constraints: ["n == matrix.length == matrix[i].length", "1 <= n <= 20"],
    hints: ["transpose first, then reverse each row."],
  },
  {
    slug: "kth-largest-element-in-array",
    title: "kth largest element in array",
    difficulty: "medium",
    topics: ["arrays", "heaps"],
    statement: "given an integer array `nums` and an integer `k`, return the kth largest element.",
    examples: [{ input: "nums = [3,2,1,5,6,4], k = 2", output: "5" }],
    constraints: ["1 <= k <= nums.length <= 10^5"],
    hints: ["min-heap of size k. or quickselect for o(n) average."],
  },
  {
    slug: "lru-cache",
    title: "lru cache",
    difficulty: "medium",
    topics: ["hashmaps", "linked lists", "system design"],
    statement: "design and implement an lru (least recently used) cache. support `get(key)` and `put(key, value)` in o(1) time.",
    examples: [{ input: "capacity = 2; put(1,1); put(2,2); get(1); put(3,3); get(2)", output: "1, then -1" }],
    constraints: ["1 <= capacity <= 3000"],
    hints: ["hashmap of key to node in a doubly linked list. move accessed node to front."],
  },
  {
    slug: "word-break",
    title: "word break",
    difficulty: "medium",
    topics: ["dp", "strings"],
    statement: "given a string `s` and a dictionary of words, return true if `s` can be segmented into one or more dictionary words.",
    examples: [{ input: "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", output: "true" }],
    constraints: ["1 <= s.length <= 300"],
    hints: ["dp[i] = true if s[0..i] is breakable."],
  },
  {
    slug: "course-schedule",
    title: "course schedule",
    difficulty: "medium",
    topics: ["graphs"],
    statement: "given `numCourses` and a list of `prerequisites` where `[a,b]` means course `a` requires course `b`, determine if you can finish all courses.",
    examples: [{ input: "numCourses = 2, prerequisites = [[1,0]]", output: "true" }],
    constraints: ["1 <= numCourses <= 2000"],
    hints: ["topological sort. detect cycles in a directed graph."],
  },
  {
    slug: "merge-intervals",
    title: "merge intervals",
    difficulty: "medium",
    topics: ["arrays", "sorting"],
    statement: "given an array of intervals where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals.",
    examples: [{ input: "[[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]" }],
    constraints: ["1 <= intervals.length <= 10^4"],
    hints: ["sort by start. iterate and merge with the last interval in result."],
  },
  {
    slug: "spiral-matrix",
    title: "spiral matrix",
    difficulty: "medium",
    topics: ["arrays"],
    statement: "given an m x n matrix, return all elements in spiral order (clockwise from top-left).",
    examples: [{ input: "[[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]" }],
    constraints: ["1 <= m, n <= 10"],
    hints: ["track four boundaries (top, bottom, left, right). shrink after each direction."],
  },
  {
    slug: "subsets",
    title: "subsets",
    difficulty: "medium",
    topics: ["recursion", "arrays"],
    statement: "given an integer array of unique elements, return all possible subsets (the power set). the solution must not contain duplicates.",
    examples: [{ input: "nums = [1,2,3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]" }],
    constraints: ["1 <= nums.length <= 10"],
    hints: ["backtracking. at each index, include or exclude."],
  },
  {
    slug: "implement-trie",
    title: "implement trie (prefix tree)",
    difficulty: "medium",
    topics: ["tries", "strings"],
    statement: "implement a trie with `insert`, `search`, and `startsWith` methods.",
    examples: [{ input: "insert(\"apple\"); search(\"apple\") -> true; search(\"app\") -> false; startsWith(\"app\") -> true" }],
    constraints: ["1 <= word.length <= 2000"],
    hints: ["each node has a children map and an isEnd flag."],
  },

  // hard
  {
    slug: "median-of-two-sorted-arrays",
    title: "median of two sorted arrays",
    difficulty: "hard",
    topics: ["arrays", "searching"],
    statement: "given two sorted arrays `nums1` and `nums2`, return the median of the two combined. the runtime should be o(log(m+n)).",
    examples: [{ input: "nums1 = [1,3], nums2 = [2]", output: "2.0" }],
    constraints: ["0 <= m, n <= 1000", "1 <= m + n"],
    hints: ["binary search the partition point in the smaller array."],
  },
  {
    slug: "trapping-rain-water",
    title: "trapping rain water",
    difficulty: "hard",
    topics: ["arrays"],
    statement: "given `n` non-negative integers representing an elevation map, compute how much water can be trapped after raining.",
    examples: [{ input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" }],
    constraints: ["1 <= height.length <= 2 * 10^4"],
    hints: ["two pointers, tracking left max and right max."],
  },
  {
    slug: "merge-k-sorted-lists",
    title: "merge k sorted lists",
    difficulty: "hard",
    topics: ["linked lists", "heaps"],
    statement: "given an array of k sorted linked lists, merge them into one sorted linked list and return it.",
    examples: [{ input: "lists = [[1,4,5],[1,3,4],[2,6]]", output: "[1,1,2,3,4,4,5,6]" }],
    constraints: ["k == lists.length", "0 <= k <= 10^4"],
    hints: ["min-heap of (value, listIndex). or divide and conquer pairwise merging."],
  },
  {
    slug: "longest-consecutive-sequence",
    title: "longest consecutive sequence",
    difficulty: "hard",
    topics: ["arrays", "hashmaps"],
    statement: "given an unsorted array of integers, return the length of the longest sequence of consecutive elements. solve in o(n).",
    examples: [{ input: "nums = [100,4,200,1,3,2]", output: "4", explanation: "the sequence is [1,2,3,4]" }],
    constraints: ["0 <= nums.length <= 10^5"],
    hints: ["hashset. only start counting from numbers where num-1 is not in the set."],
  },
  {
    slug: "word-ladder",
    title: "word ladder",
    difficulty: "hard",
    topics: ["graphs", "strings"],
    statement: "given two words `beginWord` and `endWord`, and a wordList, find the shortest transformation sequence length where each step changes exactly one letter.",
    examples: [{ input: "begin = \"hit\", end = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", output: "5" }],
    constraints: ["1 <= words.length <= 5000"],
    hints: ["bfs on a graph where edges connect words differing by one letter."],
  },
  {
    slug: "regular-expression-matching",
    title: "regular expression matching",
    difficulty: "hard",
    topics: ["dp", "strings"],
    statement: "given a string `s` and a pattern `p` supporting `.` (any char) and `*` (zero or more of preceding), return whether `p` matches the entire `s`.",
    examples: [{ input: "s = \"aa\", p = \"a*\"", output: "true" }],
    constraints: ["1 <= s.length, p.length <= 20"],
    hints: ["dp[i][j] = does p[0..j] match s[0..i]?"],
  },

  // system design lite (for interviews where these come up)
  {
    slug: "design-tinyurl",
    title: "design tinyurl",
    difficulty: "medium",
    topics: ["system design"],
    statement: "design a url shortener like tinyurl or bit.ly. discuss api, hash generation, storage, scale to billions of urls, custom aliases, analytics, and how you'd handle a viral link.",
    examples: [],
    constraints: ["this is a discussion-style problem, not a code problem."],
    hints: ["talk about base62 vs hash truncation, collision handling, cache, sharding."],
  },
  {
    slug: "design-rate-limiter",
    title: "design a rate limiter",
    difficulty: "medium",
    topics: ["system design"],
    statement: "design a rate limiter (e.g. 100 requests per minute per user). discuss algorithms (token bucket, leaky bucket, sliding window), distributed enforcement, and tradeoffs.",
    examples: [],
    constraints: ["discussion-style. consider single-server vs multi-server."],
    hints: ["token bucket is most flexible. redis is common backing store."],
  },
  {
    slug: "design-news-feed",
    title: "design a news feed",
    difficulty: "hard",
    topics: ["system design"],
    statement: "design a news feed like twitter or instagram. cover the read/write tradeoff (fanout-on-write vs fanout-on-read), celebrity user problem, ranking, and pagination.",
    examples: [],
    constraints: ["discussion. focus on tradeoffs."],
    hints: ["hybrid approach: fanout on write for normal users, on read for celebrities."],
  },

  // behavioral
  {
    slug: "tell-me-about-yourself",
    title: "tell me about yourself",
    difficulty: "easy",
    topics: ["behavioral"],
    statement: "give a 60-90 second pitch covering your background, current role/project, and what you're looking for next. avoid reading your resume line by line.",
    examples: [],
    constraints: ["keep it under 90 seconds. land on why this role/company specifically."],
    hints: ["structure: past, present, future. ~30 seconds each."],
  },
  {
    slug: "behavioral-conflict",
    title: "describe a conflict with a teammate",
    difficulty: "easy",
    topics: ["behavioral"],
    statement: "tell me about a time you disagreed with a teammate on a technical decision. what was the situation, what did you do, and what was the outcome?",
    examples: [],
    constraints: ["use star format: situation, task, action, result."],
    hints: ["focus on what you did to resolve it, not how the other person was wrong."],
  },
  {
    slug: "behavioral-failure",
    title: "tell me about a project that failed",
    difficulty: "easy",
    topics: ["behavioral"],
    statement: "describe a project or task you led that did not go well. what happened, what would you do differently, and what did you learn?",
    examples: [],
    constraints: ["pick a real failure, not a humble brag like 'i worked too hard'."],
    hints: ["the lessons learned matter more than the failure itself."],
  },

  // ml-specific (for nitish targeting mle)
  {
    slug: "ml-overfitting",
    title: "explain overfitting and how to prevent it",
    difficulty: "medium",
    topics: ["ml fundamentals"],
    statement: "what is overfitting? how do you detect it, and what techniques can prevent it? discuss bias-variance tradeoff, regularization (l1/l2), dropout, early stopping, and data augmentation.",
    examples: [],
    constraints: ["discussion. mention concrete examples."],
    hints: ["overfitting: low train error, high test error. it's variance dominating bias."],
  },
  {
    slug: "ml-precision-recall",
    title: "precision vs recall and when to use each",
    difficulty: "medium",
    topics: ["ml fundamentals"],
    statement: "explain precision, recall, f1, and roc-auc. give a scenario where you'd optimize for precision over recall, and vice versa.",
    examples: [],
    constraints: ["discussion. examples should be concrete."],
    hints: ["spam filter: precision matters more. cancer screening: recall matters more."],
  },
  {
    slug: "ml-transformer-attention",
    title: "explain self-attention in transformers",
    difficulty: "hard",
    topics: ["deep learning", "nlp"],
    statement: "walk through scaled dot-product self-attention. what are q, k, v? why scale by sqrt(d_k)? how does multi-head attention work? why does it scale better than rnns?",
    examples: [],
    constraints: ["assume the interviewer knows basic neural net concepts."],
    hints: ["q*k^t / sqrt(d_k), then softmax, then multiply by v. parallelism is the win."],
  },
  {
    slug: "ml-design-recommendation",
    title: "design a recommendation system",
    difficulty: "hard",
    topics: ["ml fundamentals", "system design"],
    statement: "design a recommendation system for a video platform (like youtube). cover candidate generation, ranking, evaluation (offline + online), cold start, and feedback loops.",
    examples: [],
    constraints: ["focus on tradeoffs. mention two-stage retrieval-then-rank architectures."],
    hints: ["candidate gen with embeddings (recall-heavy), ranker with rich features (precision-heavy)."],
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("connected to mongo");

  let inserted = 0;
  let updated = 0;
  for (const q of QUESTIONS) {
    const existing = await Question.findOne({ slug: q.slug });
    if (existing) {
      Object.assign(existing, q);
      await existing.save();
      updated++;
    } else {
      await Question.create(q);
      inserted++;
    }
  }
  console.log(`seed done. inserted=${inserted} updated=${updated} total=${QUESTIONS.length}`);
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
